-- Luxe Point V4
-- Dynamic stock + Robux/price packages + order-code rating + promo + public order tracking.

-- =========================================================
-- 1) PROMOS
-- =========================================================
create table if not exists public.promos (
  id bigint generated by default as identity primary key,
  code text unique not null,
  discount_percent numeric(5,2) not null check (discount_percent >= 0 and discount_percent <= 100),
  starts_at timestamptz not null,
  expires_at timestamptz not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (expires_at > starts_at)
);
alter table public.promos enable row level security;
drop policy if exists "public can read active promos" on public.promos;
create policy "public can read active promos" on public.promos for select to anon, authenticated using (active=true and now()>=starts_at and now()<=expires_at);
drop policy if exists "admins can read promos" on public.promos;
create policy "admins can read promos" on public.promos for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can insert promos" on public.promos;
create policy "admins can insert promos" on public.promos for insert to authenticated with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can update promos" on public.promos;
create policy "admins can update promos" on public.promos for update to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can delete promos" on public.promos;
create policy "admins can delete promos" on public.promos for delete to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
grant select on public.promos to anon;
grant select, insert, update, delete on public.promos to authenticated;

-- 2b) SEQUENCE PERMISSIONS (needed for identity inserts on newer Data API settings)
grant usage, select on sequence public.promos_id_seq to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;
grant usage, select on sequence public.order_ratings_id_seq to authenticated;


-- =========================================================
-- 2) STORE SETTINGS / GLOBAL ROBUX STOCK
-- =========================================================
create table if not exists public.store_settings (
  id integer primary key check (id=1),
  stock integer not null default 0 check (stock>=0),
  updated_at timestamptz not null default now()
);
insert into public.store_settings(id,stock) values (1,12824) on conflict(id) do nothing;
alter table public.store_settings enable row level security;
drop policy if exists "public can read store stock" on public.store_settings;
create policy "public can read store stock" on public.store_settings for select to anon, authenticated using (id=1);
drop policy if exists "admins can manage store settings" on public.store_settings;
create policy "admins can manage store settings" on public.store_settings for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
grant select on public.store_settings to anon;
grant select, insert, update, delete on public.store_settings to authenticated;

-- =========================================================
-- 3) ROBUX PRODUCTS / PACKAGES
-- =========================================================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  method text not null check (method in ('gamepass','instan')),
  robux integer not null check (robux>0),
  price bigint not null check (price>=0),
  old_price bigint,
  badge text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.products enable row level security;
drop policy if exists "public can read active products" on public.products;
create policy "public can read active products" on public.products for select to anon, authenticated using (active=true);
drop policy if exists "admins can read products" on public.products;
create policy "admins can read products" on public.products for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can insert products" on public.products;
create policy "admins can insert products" on public.products for insert to authenticated with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can update products" on public.products;
create policy "admins can update products" on public.products for update to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can delete products" on public.products;
create policy "admins can delete products" on public.products for delete to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
grant select on public.products to anon;
grant select, insert, update, delete on public.products to authenticated;

-- Seed the existing Luxe Point V3 packages only when the same package is absent.
insert into public.products(method,robux,price,old_price,badge,sort_order,active)
select * from (values
('gamepass',25,4500,null,null,1,true),('gamepass',50,8000,null,null,2,true),('gamepass',100,15000,null,null,3,true),('gamepass',200,28000,null,null,4,true),('gamepass',400,52000,null,'TERLARIS',5,true),('gamepass',800,96000,null,null,6,true),('gamepass',1000,115000,null,null,7,true),('gamepass',1700,187000,null,null,8,true),('gamepass',2500,267500,null,null,9,true),('gamepass',5000,525000,null,null,10,true),('gamepass',10000,1030000,null,null,11,true),('gamepass',22500,2250000,null,null,12,true),
('instan',25,5500,6500,null,1,true),('instan',50,10000,12000,null,2,true),('instan',100,18500,21000,null,3,true),('instan',200,34000,38000,null,4,true),('instan',400,64000,72000,'TERLARIS',5,true),('instan',800,118000,132000,null,6,true),('instan',1000,143000,160000,null,7,true),('instan',1700,230000,258000,null,8,true),('instan',2500,330000,370000,null,9,true),('instan',5000,635000,715000,null,10,true),('instan',10000,1230000,1390000,null,11,true),('instan',22500,2610000,2970000,null,12,true)
) as v(method,robux,price,old_price,badge,sort_order,active)
where not exists(select 1 from public.products p where p.method=v.method and p.robux=v.robux and p.price=v.price);

-- =========================================================
-- 4) RATING / TESTIMONIALS
-- =========================================================
create table if not exists public.order_ratings (
  id bigint generated by default as identity primary key,
  order_code text unique not null references public.orders(order_code) on delete cascade,
  name text not null,
  product text not null,
  rating integer not null check (rating between 1 and 5),
  review text not null,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.order_ratings enable row level security;
drop policy if exists "public can read approved ratings" on public.order_ratings;
create policy "public can read approved ratings" on public.order_ratings for select to anon, authenticated using (approved=true);
drop policy if exists "admins can read all ratings" on public.order_ratings;
create policy "admins can read all ratings" on public.order_ratings for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can update ratings" on public.order_ratings;
create policy "admins can update ratings" on public.order_ratings for update to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can delete ratings" on public.order_ratings;
create policy "admins can delete ratings" on public.order_ratings for delete to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
grant select on public.order_ratings to anon;
grant select, update, delete on public.order_ratings to authenticated;

-- =========================================================
-- 5) SERVER-SIDE ORDER CREATION
-- Customer sends only product ID + username + optional promo.
-- Price and Robux are read from the admin-controlled products table.
-- =========================================================
drop function if exists public.create_public_order(bigint,text,text);
create or replace function public.create_public_order(p_product_id bigint,p_roblox_username text,p_promo_code text default null)
returns table(order_code text, robux_amount integer, price bigint, promo_code text)
language plpgsql security definer set search_path=public
as $$
declare
  p public.products%rowtype;
  st integer;
  final_price bigint;
  promo_discount numeric := 0;
  normalized_code text;
  new_code text;
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  i integer;
begin
  if length(trim(p_roblox_username)) < 2 or length(trim(p_roblox_username)) > 30 then
    raise exception 'Username Roblox tidak valid.';
  end if;
  select * into p from public.products where id=p_product_id and active=true limit 1;
  if not found then raise exception 'Paket Robux tidak tersedia.'; end if;
  select stock into st from public.store_settings where id=1;
  if coalesce(st,0) < p.robux then raise exception 'Stok Robux tidak cukup.'; end if;
  normalized_code=upper(trim(coalesce(p_promo_code,'')));
  if normalized_code <> '' then
    select discount_percent into promo_discount from public.promos where upper(code)=normalized_code and active=true and now() between starts_at and expires_at limit 1;
    if promo_discount is null then raise exception 'Kode promo tidak valid atau sudah kedaluwarsa.'; end if;
  else
    normalized_code=null;
  end if;
  final_price=round(p.price*(1-(promo_discount/100)))::bigint;
  loop
    new_code='LP-'||to_char(now(),'YYYYMMDD')||'-';
    for i in 1..5 loop new_code=new_code||substr(chars,1+floor(random()*length(chars))::int,1); end loop;
    begin
      insert into public.orders(order_code,roblox_username,robux_amount,price,promo_code,status)
      values(new_code,trim(p_roblox_username),p.robux,final_price,normalized_code,'pending');
      exit;
    exception when unique_violation then
    end;
  end loop;
  return query select new_code,p.robux,final_price,normalized_code;
end; $$;
revoke all on function public.create_public_order(bigint,text,text) from public;
grant execute on function public.create_public_order(bigint,text,text) to anon, authenticated;

-- =========================================================
-- 6) PUBLIC ORDER STATUS
-- =========================================================
drop function if exists public.get_public_order_status(text);
create or replace function public.get_public_order_status(p_order_code text)
returns table(order_code text,roblox_username text,robux_amount integer,price bigint,promo_code text,status text,created_at timestamptz)
language sql security definer set search_path=public
as $$
  select o.order_code,o.roblox_username,o.robux_amount,o.price,o.promo_code,o.status,o.created_at
  from public.orders o where upper(o.order_code)=upper(trim(p_order_code)) limit 1;
$$;
revoke all on function public.get_public_order_status(text) from public;
grant execute on function public.get_public_order_status(text) to anon, authenticated;

-- =========================================================
-- 7) RATING SUBMISSION: only completed orders, one rating/order
-- =========================================================
drop function if exists public.submit_order_rating(text,text,text,integer,text);
create or replace function public.submit_order_rating(p_order_code text,p_name text,p_product text,p_rating integer,p_review text)
returns json
language plpgsql security definer set search_path=public
as $$
declare st text; normalized text; result json;
begin
  normalized=upper(trim(p_order_code));
  select status into st from public.orders where upper(order_code)=normalized limit 1;
  if st is null then raise exception 'Order ID tidak ditemukan.'; end if;
  if st <> 'completed' then raise exception 'Rating hanya bisa diberikan setelah order berstatus selesai.'; end if;
  if exists(select 1 from public.order_ratings where upper(order_code)=normalized) then raise exception 'Order ini sudah pernah memberikan rating.'; end if;
  insert into public.order_ratings(order_code,name,product,rating,review,approved)
  values(normalized,trim(p_name),trim(p_product),p_rating,trim(p_review),false)
  returning json_build_object('id',id,'order_code',order_code) into result;
  return result;
end; $$;
revoke all on function public.submit_order_rating(text,text,text,integer,text) from public;
grant execute on function public.submit_order_rating(text,text,text,integer,text) to anon, authenticated;

-- =========================================================
-- 8) REALTIME
-- =========================================================
alter table public.orders replica identity full;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='orders') then
    alter publication supabase_realtime add table public.orders;
  end if;
exception when others then null; end $$;
